version: '3'
services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  api-gw:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DATABASE=apigw
      - HTTP_PORT=8080
    volumes:
      - ./webadmin:/app/webadmin
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem